# Site settings
title: Lucas's blog 
email: lucas.gerbeaux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Lucas, I write (rarely) about what I like. 
  This includes technology, philosophy, finance, business, startups...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucas.gerbeaux.com" # the base hostname & protocol for your site
twitter_username: lgerbeaux
github_username:  gbxl

# Build settings
markdown: kramdown
